// <auto-generated />
using System;
using HomeInventory3D.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HomeInventory3D.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    partial class InventoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HomeInventory3D.Domain.Entities.Container", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<float?>("DepthMm")
                        .HasColumnType("real")
                        .HasColumnName("depth_mm");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<float?>("HeightMm")
                        .HasColumnType("real")
                        .HasColumnName("height_mm");

                    b.Property<DateTime?>("LastScannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_scanned_at");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("location");

                    b.Property<string>("MeshFilePath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("mesh_file_path");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("NfcId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nfc_id");

                    b.Property<string>("QrCode")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("qr_code");

                    b.Property<string>("ThumbnailPath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("thumbnail_path");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<float?>("WidthMm")
                        .HasColumnType("real")
                        .HasColumnName("width_mm");

                    b.HasKey("Id");

                    b.HasIndex("NfcId")
                        .IsUnique()
                        .HasFilter("nfc_id IS NOT NULL");

                    b.HasIndex("QrCode")
                        .IsUnique()
                        .HasFilter("qr_code IS NOT NULL");

                    b.ToTable("containers", (string)null);
                });

            modelBuilder.Entity("HomeInventory3D.Domain.Entities.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<float?>("BboxMaxX")
                        .HasColumnType("real")
                        .HasColumnName("bbox_max_x");

                    b.Property<float?>("BboxMaxY")
                        .HasColumnType("real")
                        .HasColumnName("bbox_max_y");

                    b.Property<float?>("BboxMaxZ")
                        .HasColumnType("real")
                        .HasColumnName("bbox_max_z");

                    b.Property<float?>("BboxMinX")
                        .HasColumnType("real")
                        .HasColumnName("bbox_min_x");

                    b.Property<float?>("BboxMinY")
                        .HasColumnType("real")
                        .HasColumnName("bbox_min_y");

                    b.Property<float?>("BboxMinZ")
                        .HasColumnType("real")
                        .HasColumnName("bbox_min_z");

                    b.Property<float?>("Bounciness")
                        .HasColumnType("real")
                        .HasColumnName("bounciness");

                    b.Property<string>("ColliderType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("collider_type");

                    b.Property<float?>("Confidence")
                        .HasColumnType("real")
                        .HasColumnName("confidence");

                    b.Property<Guid>("ContainerId")
                        .HasColumnType("uuid")
                        .HasColumnName("container_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<float?>("Friction")
                        .HasColumnType("real")
                        .HasColumnName("friction");

                    b.Property<bool?>("IsFragile")
                        .HasColumnType("boolean")
                        .HasColumnName("is_fragile");

                    b.Property<float?>("MassKg")
                        .HasColumnType("real")
                        .HasColumnName("mass_kg");

                    b.Property<string>("MaterialType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("material_type");

                    b.Property<string>("MeshFilePath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("mesh_file_path");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("photo_path");

                    b.Property<float?>("PositionX")
                        .HasColumnType("real")
                        .HasColumnName("position_x");

                    b.Property<float?>("PositionY")
                        .HasColumnType("real")
                        .HasColumnName("position_y");

                    b.Property<float?>("PositionZ")
                        .HasColumnType("real")
                        .HasColumnName("position_z");

                    b.Property<float?>("RealSizeCm")
                        .HasColumnType("real")
                        .HasColumnName("real_size_cm");

                    b.Property<string>("RecognitionSource")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("recognition_source");

                    b.Property<float?>("RotationX")
                        .HasColumnType("real")
                        .HasColumnName("rotation_x");

                    b.Property<float?>("RotationY")
                        .HasColumnType("real")
                        .HasColumnName("rotation_y");

                    b.Property<float?>("RotationZ")
                        .HasColumnType("real")
                        .HasColumnName("rotation_z");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Present")
                        .HasColumnName("status");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("tags")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("ThumbnailPath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("thumbnail_path");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId")
                        .HasDatabaseName("idx_items_container");

                    b.HasIndex("Name")
                        .HasDatabaseName("idx_items_name_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_items_status");

                    b.HasIndex("Tags")
                        .HasDatabaseName("idx_items_tags");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Tags"), "gin");

                    b.ToTable("inventory_items", (string)null);
                });

            modelBuilder.Entity("HomeInventory3D.Domain.Entities.ScanSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContainerId")
                        .HasColumnType("uuid")
                        .HasColumnName("container_id");

                    b.Property<string>("DepthMapPath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("depth_map_path");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<int>("ItemsAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("items_added");

                    b.Property<int>("ItemsDetected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("items_detected");

                    b.Property<int>("ItemsRemoved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("items_removed");

                    b.Property<string>("PointCloudPath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("point_cloud_path");

                    b.Property<string>("RgbPhotoPath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("rgb_photo_path");

                    b.Property<string>("ScanType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("scan_type");

                    b.Property<DateTime>("ScannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scanned_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId");

                    b.ToTable("scan_sessions", (string)null);
                });

            modelBuilder.Entity("HomeInventory3D.Domain.Entities.InventoryItem", b =>
                {
                    b.HasOne("HomeInventory3D.Domain.Entities.Container", "Container")
                        .WithMany("Items")
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Container");
                });

            modelBuilder.Entity("HomeInventory3D.Domain.Entities.ScanSession", b =>
                {
                    b.HasOne("HomeInventory3D.Domain.Entities.Container", "Container")
                        .WithMany("ScanSessions")
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Container");
                });

            modelBuilder.Entity("HomeInventory3D.Domain.Entities.Container", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("ScanSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
